### ISSUE TITLE
Remove unused files, blueprints and folders.

### ISSUE THREAD

**Issue by Vishwamithra37** [Vishwamithra37/Slots#22]
Follow conventions 
![image](https://github.com/Vishwamithra37/Slots/assets/53423141/7abf7497-1a94-4a48-ba68-2c1575b6f72c)

**Comment by NavyaSree27** [comment]
I am not using that file( routes) vishwa. I think It was created before we assigned tasks among us.

**Comment by Vishwamithra37** [comment]
@NavyaSree27 then please make a branch and delete unused files
![image](https://github.com/Vishwamithra37/Slots/assets/53423141/b16f3ddd-d40f-4b7b-97a4-3874c682ad15)
